export const APP_TYPE = {
    FETCH_APP_REQUEST: "app/FETCH_APP_REQUEST",
    FETCH_APP_SUCCESS: "app/FETCH_APP_SUCCESS",
    FETCH_APP_FAILURE: "app/FETCH_APP_FAILURE",
};
export const TOGGLE_SIDEBAR = "app/TOGGLE_SIDEBAR";
